# Generated by Django 3.2.7 on 2021-10-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='language',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
