# Generated by Django 3.2.7 on 2021-11-22 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0002_alter_session_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caregiver',
            old_name='caregiver_id',
            new_name='ccid',
        ),
        migrations.RenameField(
            model_name='caregiver',
            old_name='caregiver_data',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_id',
            new_name='clid',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_data',
            new_name='data',
        ),
    ]
