# Generated by Django 4.0.1 on 2022-02-17 16:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0004_auto_20211217_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_text', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('entities', models.JSONField(null=True)),
                ('replacement_text', models.TextField(null=True)),
                ('type', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='session',
        ),
        migrations.RemoveField(
            model_name='session',
            name='caregiver',
        ),
        migrations.RemoveField(
            model_name='session',
            name='client',
        ),
        migrations.DeleteModel(
            name='Caregiver',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Sentence',
        ),
        migrations.AddField(
            model_name='textdata',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REST.session'),
        ),
    ]
